In [4]:
# 1. Create a scalar tensor with value 10 using tf.constant and print its value and data type.

import tensorflow as tf
import numpy
scalar=tf.constant(10)
print(f"Scalar Shape:{scalar.shape}, Scalar Value:{scalar.numpy()}")

Scalar Shape:(), Scalar Value:10


In [5]:
# 2. Create a 1-D tensor (vector) [2, 4, 6, 8] using tf.constant and print its shape and numpy value.
vector=tf.constant([2, 4, 6, 8])
print(f"Vector Shape:{vector.shape}, Vector Value:{vector.numpy()}")

Vector Shape:(4,), Vector Value:[2 4 6 8]


In [12]:
# 3. Create a 2-D tensor (matrix) [[1, 2], [3, 4]] using tf.constant and print its shape and dtype.
matrix=tf.constant([[1, 2], [3, 4]])
print(f"Matrix Shape:{matrix.shape}\n Matrix Value:\n{matrix.numpy()}\n Matrix Type:{matrix.dtype}")

Matrix Shape:(2, 2)
 Matrix Value:
[[1 2]
 [3 4]]
 Matrix Type:<dtype: 'int32'>


In [14]:
# 4. Create a tf.Variable with initial value 5.0 and print its current value.

temp=tf.Variable(5.0)
print("Value of temp:",temp.numpy())

Value of temp: 5.0


In [15]:
# 5. Update the above variable by assigning it a new value 10.0 using assign() and print the updated value.
temp.assign(10.0)
print("Updated Value of temp:",temp.numpy())

Updated Value of temp: 10.0


In [18]:
# 6. Use assign_add() on a variable initialized with [[1.0, 2.0], [3.0, 4.0]] to add 1.0 to every element and print the result.

temp2=tf.Variable([[1.0, 2.0], [3.0, 4.0]])
temp2.assign_add([[1.0,1.0],[1.0,1.0]])

print("Updated Value of temp:\n",temp2.numpy())

Updated Value of temp:
 [[2. 3.]
 [4. 5.]]


In [21]:
# 9. Create two constant tensors a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]] and perform matrix multiplication 
# using tf.matmul().

a=tf.constant([[1,2],[3,4]])
b=tf.constant([[5,6],[7,8]])

print("Matrix Multiplication is:\n",tf.matmul(a,b).numpy())



Matrix Multiplication is:
 [[19 22]
 [43 50]]


In [25]:
# 10. Create a random tensor of shape (3, 3) using tf.random.uniform() and print its shape, dtype, and values.

tens = tf.random.uniform(shape=(3, 3))
print(tens.numpy())

print(tens.shape)
print(tens.dtype)


[[0.58010614 0.32530367 0.00921702]
 [0.3660308  0.4128369  0.58194506]
 [0.65711105 0.37360394 0.28203046]]
(3, 3)
<dtype: 'float32'>
